import { Product, Sale } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    sku: 'VV-KANJ-001',
    title: 'Maharani Ratna Kanjeevaram Bridal Silk Saree',
    slug: 'maharani-ratna-kanjeevaram-bridal-silk',
    category: 'Saree',
    weave: 'Kanjeevaram Silk',
    fabric: 'Pure 100% Mulberry Silk (Certified Silk Mark)',
    zari_type: 'Pure Gold Zari (Tested Silver & Gold Wire)',
    color: 'Temple Crimson & Antique Gold',
    color_variants: [
      { colorName: 'Temple Crimson & Gold', hexCode: '#7A1228', quantity: 1 },
      { colorName: 'Peacock Royal Blue & Zari', hexCode: '#102A45', quantity: 1 },
    ],
    description:
      'A masterpiece of South Indian heritage weaving. Woven on traditional pit-looms by master artisans with pure mulberry silk yarns. Features the sacred Mayil (peacock) and Rudraksha motifs along the heavy contrast border and a grand architectural pallu.',
    blouse_details: 'Includes 0.8m running unstitched pure silk blouse piece with matching rich zari sleeve border.',
    length_meters: 6.2,
    buying_price: 14500,
    selling_price: 26800,
    stock_quantity: 2,
    images: ['/images/products/kanjeevaram-crimson.jpg'],
    is_featured: true,
    is_active: true,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prod-002',
    sku: 'VV-BAN-002',
    title: 'Virasat Kadwa Emerald Banarasi Silk Saree',
    slug: 'virasat-kadwa-emerald-banarasi-silk',
    category: 'Saree',
    weave: 'Banarasi Brocade',
    fabric: 'Pure Katan Silk',
    zari_type: 'Antique Gold Zari Kadwa Brocade',
    color: 'Peacock Emerald & Antique Gold',
    color_variants: [
      { colorName: 'Peacock Emerald Green', hexCode: '#0A3B32', quantity: 2 },
      { colorName: 'Royal Midnight Violet', hexCode: '#3D1C4E', quantity: 1 },
    ],
    description:
      'Timeless Banarasi craftsmanship featuring pure Katan silk with all-over intricate Kadwa floral jaal hand-embroidered with antique zari. The fluid drape and regal luster make it an heirloom piece for receptions and grand celebrations.',
    blouse_details: 'Unstitched matching emerald green pure silk blouse with intricate border motifs.',
    length_meters: 6.2,
    buying_price: 11200,
    selling_price: 21500,
    stock_quantity: 3,
    images: ['/images/products/banarasi-emerald.jpg'],
    is_featured: true,
    is_active: true,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prod-003',
    sku: 'VV-ORG-003',
    title: 'Gulab Bahaar Scalloped Organza Tissue Silk Saree',
    slug: 'gulab-bahaar-scalloped-organza-tissue-silk',
    category: 'Saree',
    weave: 'Organza Tissue',
    fabric: 'Pure Sheer Organza Tissue with Luminous Silk Sheen',
    zari_type: 'Handcrafted Golden Zari Scalloped Floral Embroidery',
    color: 'Blush Rose & Champagne Gold',
    color_variants: [
      { colorName: 'Blush Rose Pink', hexCode: '#E8A598', quantity: 2 },
      { colorName: 'Champagne Ivory Gold', hexCode: '#F3E5AB', quantity: 2 },
    ],
    description:
      'Ethereal, lightweight, and modern. Crafted on fine organza tissue with hand-cut scalloped borders finished with delicate gold zari cutwork and micro-sequin florals. Perfect for cocktail evenings, daytime weddings, and engagement soirees.',
    blouse_details: 'Includes heavy embroidered designer blouse fabric in matching blush tone.',
    length_meters: 6.2,
    buying_price: 6800,
    selling_price: 13900,
    stock_quantity: 4,
    images: ['/images/products/organza-rose.jpg'],
    is_featured: true,
    is_active: true,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prod-004',
    sku: 'VV-PAI-004',
    title: 'Rajkanya Mor-Pankh Mustard Paithani Silk Saree',
    slug: 'rajkanya-mor-pankh-mustard-paithani-silk',
    category: 'Saree',
    weave: 'Paithani Silk',
    fabric: 'Pure Handloom Silk',
    zari_type: 'Intricate Peacock Zari Pallu with Tapestry Silk Borders',
    color: 'Royal Mustard Yellow & Multi-tone Zari',
    color_variants: [
      { colorName: 'Royal Mustard Gold', hexCode: '#C8961D', quantity: 1 },
    ],
    description:
      'The queen of Maharashtrian weaves. Features the iconic Asawali and peacock motifs meticulously woven using the tapestry technique. Lustrous mustard gold body paired with an elaborate multi-hued floral zari pallu.',
    blouse_details: 'Contrasting silk unstitched blouse piece with matching peacock border.',
    length_meters: 6.2,
    buying_price: 13000,
    selling_price: 24000,
    stock_quantity: 1,
    images: ['/images/products/paithani-mustard.jpg'],
    is_featured: true,
    is_active: true,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale-001',
    product_id: 'prod-001',
    sku: 'VV-KANJ-001',
    product_title: 'Maharani Ratna Kanjeevaram Bridal Silk Saree',
    selected_color: 'Temple Crimson & Gold',
    quantity: 1,
    unit_cost_price: 14500,
    unit_sale_price: 26800,
    total_revenue: 26800,
    total_profit: 12300,
    channel: 'WhatsApp',
    customer_name: 'Priya Sharma (Bengaluru)',
    customer_phone: '+91 98450 12345',
    notes: 'Bride order for Muhurtham ceremony; customized fall & pico requested.',
    sale_date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'sale-002',
    product_id: 'prod-003',
    sku: 'VV-ORG-003',
    product_title: 'Gulab Bahaar Scalloped Organza Tissue Silk Saree',
    selected_color: 'Blush Rose Pink',
    quantity: 1,
    unit_cost_price: 6800,
    unit_sale_price: 13900,
    total_revenue: 13900,
    total_profit: 7100,
    channel: 'In-Store',
    customer_name: 'Ananya Rao (Boutique Walk-in)',
    customer_phone: '+91 99800 67890',
    notes: 'Selected after live in-store drape trial for sangeet party.',
    sale_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'sale-003',
    product_id: 'prod-002',
    sku: 'VV-BAN-002',
    product_title: 'Virasat Kadwa Emerald Banarasi Silk Saree',
    selected_color: 'Peacock Emerald Green',
    quantity: 1,
    unit_cost_price: 11200,
    unit_sale_price: 21500,
    total_revenue: 21500,
    total_profit: 10300,
    channel: 'Instagram',
    customer_name: 'Deepa Reddy (Hyderabad)',
    customer_phone: '+91 97000 54321',
    notes: 'Inquired on DM, finalized on WhatsApp with express courier.',
    sale_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
